### ISSUE TITLE
Minified and unminified files

### ISSUE THREAD

**Issue by paulozoom** [bramstein/trmix#3]
It might be useful to include an unminified version of trmix in the dist folder, and rename the actual file to `trmix.min.js`.

Not only because it's easier for people to read the code and learn how it's done, but also because it's standard practice in frontend JS libraries. That would also let people concat all the libraries in their projects, and then run minification and the very end.

It seems that grunt-closure-compiler minifies by default, and I've been through its options and couldn't find an option to avoid that.

**Comment by bramstein** [comment]
I've added a `trmix.min.js` and a debug version `trmix.js` to the dist directory. It turned out a bit more complicated due to the Closure dependency system. So the current unminified version isn't an exact match with the source files, but I think it is a decent middle ground.

Thanks for the suggestion, and a merry christmas!

**Comment by paulozoom** [comment]
Thanks!
